#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ems?createDatabaseIfNotExist=true&serverTimezone=UTC
#    username: root
#    password: root1
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: false
#    show-sql: false
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#main:
#  allow-bean-definition-overriding: true
#
#flyway:
#  locations: classpath:db/migration
#  baseline-on-migrate: true
#  user: root
#  password: root1
#  url: jdbc:mysql://localhost:3306
#
#server:
#  port: 9090